name: Force RC alignment
description: "Ensures RC patch increments when only fix commits are present, adding a Release-As footer to guide release-please."

inputs:
  target-ref:
    description: "Full Git ref to run on (e.g., refs/heads/next). Steps are skipped if the current ref doesn't match."
    required: false
    default: refs/heads/next

outputs:
  next_version:
    description: "Calculated RC version when only fixes exist."
    value: ${{ steps.calc.outputs.next_version }}

runs:
  using: composite
  steps:
    - name: Setup Python
      if: ${{ github.ref == inputs.target-ref }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Checkout
      if: ${{ github.ref == inputs.target-ref }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Calculate Correct RC Version (Python)
      id: calc
      if: ${{ github.ref == inputs.target-ref }}
      shell: bash
      run: |
        python3 "$GITHUB_ACTION_PATH/rc_align.py" calc

    - name: Inject Release-As Footer (Python)
      if: ${{ github.ref == inputs.target-ref && steps.calc.outputs.next_version != '' }}
      shell: bash
      run: |
        python3 "$GITHUB_ACTION_PATH/rc_align.py" inject "${{ steps.calc.outputs.next_version }}"
